Ft user signup functionality 162170979
andela/heimdal-ah-frontend pull request #17
Opened 2019-01-21 08:47 UTC by henperi

#### What does this PR do?
- It integrates functionality for users to signup from the front end

#### Description of Task to be completed?

#### How should this be manually tested?

#### What are the relevant pivotal tracker stories?

#### Any background context you want to add?

#### Screenshots

2019-01-25 14:27 UTC, edogbosunny approved these changes

2019-01-25 14:54 UTC, pitaz approved these changes

2019-01-25 15:05 UTC, akpante3 approved these changes

2019-01-25 15:08 UTC, el-Joft approved these changes

2019-01-26 10:54 UTC, akpante3 commented
hi! @henperi  Nice work, but you can do better on this fewature

2019-01-26 11:07 UTC, akpante3 commented
hi @henperi  Nice work, but I don't like how you implemented this feature...you can do better.

2019-01-26 21:21 UTC, sudhons requested changes

2019-01-26 21:21 UTC, sudhons commented on src/component/Layout/MainLayout/MainLayout.jsx
> +    </main>
@henperi, please why is the `MainLayout` component connected to redux store? Also passing `auth.user.user.username` to the header, will raise an error if the user is not authenticated and why are we having`main`with a padding. Also, what is the purpose of the `container-fluid` div in all of our pages?

2019-01-28 05:24 UTC, henperi commented on src/component/Layout/MainLayout/MainLayout.jsx
> +    </main>
I have fixed the main layout connection to redux. Thanks. I have also fixed the ```auth.user.user.username``` issue. 

I previously set the navigation bar to be fixed at the top of the website. So to make sure the nav doesn't sit on the main I had to give it top padding. Outside of this, the main section looks too close to the navigation bar. A little padding adds some aesthetic pleasance in my opinion. 

The ```container-fluid``` or ```container``` class is a basic requirement while using bootstrap 4 grid layout system. 
<img width="759" alt="screen shot 2019-01-28 at 6 20 26 am" src="https://user-images.githubusercontent.com/36136977/51816142-7d717500-22c5-11e9-8334-0e41fcfb13d1.png">

Please refer to the bootstrap docs for more info https://getbootstrap.com/docs/4.2/layout/overview/

2019-01-28 09:01 UTC, merged