#162170988 article glow functionality
andela/heimdal-ah-frontend pull request #35
Opened 2019-02-02 15:17 UTC by pitaz

#### What does this PR do?
Add article glow functionality

#### Description of Task to be completed?
- Write test
- add `handleGlow` functionality to glow component
- Create actions and reducers
#### How should this be manually tested?
- git clone project
- start server executing `npm run start`
#### What are the relevant pivotal tracker stories?
- [#162170988](https://www.pivotaltracker.com/story/show/162170988)
#### Any background context you want to add?
- None
#### Screenshots
- Nil

2019-02-02 16:41 UTC, sudhons requested changes

2019-02-02 16:41 UTC, sudhons commented on src/component/ui/ArticleLike/ArticleLike.jsx
> +export default ArticleLike;
If this file is not used anywhere can we please remove it. Line 12 is strange.

2019-02-02 16:41 UTC, sudhons commented on src/component/ui/Buttons/glow/Glow.jsx
> +// export default connect(mapStateToProps, mapDispatchToProps)(Glow);
Please let's remove these comments if we won't be using them

2019-02-03 19:09 UTC, edogbosunny approved these changes

2019-02-04 09:46 UTC, rentgratatech approved these changes

2019-02-04 10:33 UTC, sudhons approved these changes

2019-02-04 18:02 UTC, henperi approved these changes

2019-02-04 18:40 UTC, merged